name: llama.cpp configuration
version: 1.0.0
schema: v1
models:
  - name: IBM Granite 4 Tiny
    provider: llama.cpp
    model: granite-4-h-tiny
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    capabilities:
      - tool_use
  - name: NVidia Nemotron 3 Nano
    provider: llama.cpp
    model: nemotron-3-nano-4b
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    capabilities:
      - tool_use
  - name: Gemma 4
    provider: llama.cpp
    model: google/gemma-4-e4b
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    capabilities:
      - tool_use
  - name: Phi4 Reasoning Plus
    provider: llama.cpp
    model: microsoft/phi-4-reasoning-plus
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    capabilities:
      - tool_use
  - name: Qwen 3.5 9B
    provider: llama.cpp
    model: Qwen3.5-9B-GGUF
    roles:
      - apply
      - autocomplete
      - chat
      - edit
      - summarize
    capabilities:
      - tool_use
      - next_edit
  - name: Zerank 2.0
    provider: llama.cpp
    model: zerank-2-GGUF/zerank-2.Q4_K_S.gguf
    roles:
      - rerank
      - embed
context:
  - provider: repo-map
    params:
      includeSignatures: true # default true
  - provider: os
  - provider: diff
  - provider: file
  - provider: code
  - provider: open
  - provider: tree
  - provider: currentFile
